# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

l1 = Location.create(city: "Moab", state: "Utah")
l2 = Location.create(city: "Washington County", state: "Utah")
l3 = Location.create(city: "Whitehall", state: "Montana")
l4 = Location.create(city: "Boulder", state: "Montana")
l5 = Location.create(city: "Pineville", state: "Missouri")
l6 = Location.create(city: "Cassville", state: "Missouri")
l7 = Location.create(city: "Scenic", state: "South Dakota")
l8 = Location.create(city: "Scenic", state: "South Dakota")
l9 = Location.create(city: "Moab", state: "California")
l10 = Location.create(city: "Moab", state: "California")
l11 = Location.create(city: "Moab", state: "Tennessee")
l12 = Location.create(city: "Moab", state: "Tennessee")
l13 = Location.create(city: "Moab", state: "Texas")
l14 = Location.create(city: "Moab", state: "Texas")
l14 = Location.create(city: "Moab", state: "Colorado")
l14 = Location.create(city: "Moab", state: "Colorado")
l14 = Location.create(city: "Moab", state: "Arizona")
l14 = Location.create(city: "Moab", state: "Arizona")
l14 = Location.create(city: "Moab", state: "Alaska")
l14 = Location.create(city: "Moab", state: "Alaska")

u1 = User.find_by(id: 1, name: "Deryn")

t1 = Trail.create(name: "Poison Spider Mesa", length: "10 miles", difficulty: "Moderate", location_id: l1.id)
t2 = Trail.create(name: "Sand Hollow State Park", length: "Unknown miles", difficulty: "Moderate", location_id: l2.id)
t3 = Trail.create(name: "Ringing Rocks Trail", length: "12.7 miles", difficulty: "Hard", location_id: l3.id)
t4 = Trail.create(name: "Elkhorn and Crow Peak Trail", length: "7.9 miles", difficulty: "Hard", location_id: l4.id)
t5 = Trail.create(name: "Rush Springs Ranch OHV Route", length: "6.0 miles", difficulty: "Moderate", location_id: l5.id)
t6 = Trail.create(name: "Sugar Camp Scenic Byway", length: "18.5 miles", difficulty: "Easy", location_id: l6.id)
t7 = Trail.create(name: "Sheep Mountain Table Road", length: "14.6 miles", difficulty: "Moderate", location_id: l7.id)
t8 = Trail.create(name: "Cedar Butte Trail", length: "1.3 miles", difficulty: "Moderate", location_id: l8.id)

ut1 = UserTrails.create(user_id: u1.id, trail_id: t1.id, completed: false)
ut2 = UserTrails.create(user_id: u1.id, trail_id: t2.id, completed: false)
ut3 = UserTrails.create(user_id: u1.id, trail_id: t3.id, completed: false)
ut4 = UserTrails.create(user_id: u1.id, trail_id: t4.id, completed: false)
ut5 = UserTrails.create(user_id: u1.id, trail_id: t5.id, completed: false)
ut6 = UserTrails.create(user_id: u1.id, trail_id: t6.id, completed: false)
ut7 = UserTrails.create(user_id: u1.id, trail_id: t7.id, completed: false)
ut8 = UserTrails.create(user_id: u1.id, trail_id: t8.id, completed: false)
ut9 = UserTrails.create(user_id: u1.id, trail_id: t9.id, completed: false)
ut10 = UserTrails.create(user_id: u1.id, trail_id: t10.id, completed: false)
ut11 = UserTrails.create(user_id: u1.id, trail_id: t11.id, completed: false)
ut12 = UserTrails.create(user_id: u1.id, trail_id: t12.id, completed: false)
ut13 = UserTrails.create(user_id: u1.id, trail_id: t13.id, completed: false)
ut14 = UserTrails.create(user_id: u1.id, trail_id: t14.id, completed: false)
ut15 = UserTrails.create(user_id: u1.id, trail_id: t15.id, completed: false)
ut16 = UserTrails.create(user_id: u1.id, trail_id: t16.id, completed: false)